<script lang="ts" setup>
import { ref } from 'vue';
import LPic from './LPic.vue';

// Directly declare testImages as objects matching LPic props
const testImages = ref([
  {
    src: '/img/button_card_change_back',
    ext: 'svg',
    usePrefix: false,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/button_card_click_left',
    ext: 'svg',
    usePrefix: false,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/button_card_click_right',
    ext: 'svg',
    usePrefix: false,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/button_card_flip',
    ext: 'svg',
    usePrefix: false,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/button_card_plus_corner',
    ext: 'svg',
    usePrefix: false,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/button_click_down_below',
    ext: 'svg',
    usePrefix: false,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_love_blue01',
    ext: 'svg',
    usePrefix: false,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_love_blue02',
    ext: 'svg',
    usePrefix: false,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_love_red01',
    ext: 'svg',
    usePrefix: false,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_love_red02',
    ext: 'svg',
    usePrefix: false,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p01_frame01_00_pcpad',
    ext: 'jpg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p01_frame01_00_pcpad',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p01_frame01_01_mob',
    ext: 'png',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p01_frame01_01_mob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p01_frame01_01_pcpad',
    ext: 'png',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p01_frame01_01_pcpad',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p01_frame01_02_mob',
    ext: 'png',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p01_frame01_02_mob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p01_frame01_02_pcpad',
    ext: 'png',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p01_frame01_02_pcpad',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p01_frame01_03_mob',
    ext: 'png',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p01_frame01_03_mob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p01_frame01_03_pcpad',
    ext: 'png',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p01_frame01_03_pcpad',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p01_frame02_04_mob',
    ext: 'png',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p01_frame02_04_mob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p01_frame02_04_pcpad',
    ext: 'png',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p01_frame02_04_pcpad',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p01_frame03_05_mob',
    ext: 'png',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p01_frame03_05_mob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p01_frame03_05_pcpad',
    ext: 'png',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p01_frame03_05_pcpad',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p01_frame04_06_mob',
    ext: 'png',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p01_frame04_06_mob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p01_frame04_06_pcpad',
    ext: 'png',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p01_frame04_06_pcpad',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p01_frame04_07_mob',
    ext: 'png',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p01_frame04_07_mob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p01_frame04_07_pcpad',
    ext: 'png',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p01_frame04_07_pcpad',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p01_frame04_08_mob',
    ext: 'png',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p01_frame04_08_mob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p01_frame04_08_pcpad',
    ext: 'png',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p01_frame04_08_pcpad',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p01_frame05_09_mob',
    ext: 'png',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p01_frame05_09_mob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p01_frame05_09_pcpad',
    ext: 'png',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p01_frame05_09_pcpad',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p01_frame06_10_mob',
    ext: 'jpg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p01_frame06_10_mob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p01_frame06_10_pcpad',
    ext: 'jpg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p01_frame06_10_pcpad',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0201_dialogbox_pad',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0201_maintext_01_mob',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0201_maintext_01_pcpad',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0201_maintext_02_mob',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0201_maintext_02_pcpad',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0202_card03_info_mob',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0202_card03_info_pad',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0202_card03_info_pc',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0202_card04_info01_mob',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0202_card04_info01_pad',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0202_card04_info01_pc',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0202_card04_info02_mob',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0202_card04_info02_pad',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0202_card04_info02_pc',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0202_card04_info03_mob',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0202_card04_info03_pad',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0202_card04_info03_pc',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0202_card04_info04_mob',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0202_card04_info04_pad',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0202_card04_info04_pc',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0202_card04_info05_mob',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0202_card04_info05_pad',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0202_card04_info05_pc',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0202_card05_info_mob',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0202_card05_info_pad',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0202_card06_info_mob',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0202_card06_info_pad',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0202_card06_info_pc',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0301_dialogbox_mob',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0301_dialogbox_pad',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0301_dialogbox_pc',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0302_card01_piccir_b_pcpadmob',
    ext: 'png',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0302_card01_piccir_b_pcpadmob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0302_card01_piccir_s_pcpadmob',
    ext: 'png',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0302_card01_piccir_s_pcpadmob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0302_card01_picsq_mob',
    ext: 'jpg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0302_card01_picsq_mob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0302_card01_picsq_pcpad',
    ext: 'jpg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0302_card01_picsq_pcpad',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0302_card02_piccir_b_pcpadmob',
    ext: 'png',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0302_card02_piccir_b_pcpadmob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0302_card02_piccir_s_pcpadmob',
    ext: 'png',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0302_card02_piccir_s_pcpadmob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0302_card02_picsq_mob',
    ext: 'jpg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0302_card02_picsq_mob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0302_card02_picsq_pcpad',
    ext: 'jpg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0302_card02_picsq_pcpad',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0302_card03_piccir_b_pcpadmob',
    ext: 'png',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0302_card03_piccir_b_pcpadmob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0302_card03_piccir_s_pcpadmob',
    ext: 'png',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0302_card03_piccir_s_pcpadmob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0302_card03_picsq_mob',
    ext: 'jpg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0302_card03_picsq_mob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0302_card03_picsq_pcpad',
    ext: 'jpg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0302_card03_picsq_pcpad',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0302_card04_piccir_b_pcpadmob',
    ext: 'png',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0302_card04_piccir_b_pcpadmob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0302_card04_piccir_s_pcpadmob',
    ext: 'png',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0302_card04_piccir_s_pcpadmob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0302_card04_picsq_mob',
    ext: 'jpg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0302_card04_picsq_mob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0302_card04_picsq_pcpad',
    ext: 'jpg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0302_card04_picsq_pcpad',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0302_card05_piccir_b_pcpadmob',
    ext: 'png',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0302_card05_piccir_b_pcpadmob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0302_card05_piccir_s_pcpadmob',
    ext: 'png',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0302_card05_piccir_s_pcpadmob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0302_card05_picsq_mob',
    ext: 'jpg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0302_card05_picsq_mob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0302_card05_picsq_pcpad',
    ext: 'jpg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0302_card05_picsq_pcpad',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0302_card06_piccir_b_pcpadmob',
    ext: 'png',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0302_card06_piccir_b_pcpadmob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0302_card06_piccir_s_pcpadmob',
    ext: 'png',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0302_card06_piccir_s_pcpadmob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0302_card06_picsq_mob',
    ext: 'jpg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0302_card06_picsq_mob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0302_card06_picsq_pcpad',
    ext: 'jpg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0302_card06_picsq_pcpad',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0401_dialogbox_mob',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0401_dialogbox_pc',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0402_heartsign_pcpadmob',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0403_piccir_liora_pcpadmob',
    ext: 'png',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0403_piccir_liora_pcpadmob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0403_piccir_luma_pcpadmob',
    ext: 'png',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0403_piccir_luma_pcpadmob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0404_picsq_liora__pcpadmob',
    ext: 'jpg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0404_picsq_liora__pcpadmob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0404_picsq_luma__pcpadmob',
    ext: 'jpg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0404_picsq_luma__pcpadmob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0405_picsq01_luma__pcpadmob',
    ext: 'jpg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0405_picsq01_luma__pcpadmob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0405_picsq02_luma__pcpadmob',
    ext: 'jpg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0405_picsq02_luma__pcpadmob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0501_dialogbox_mob',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0501_dialogbox_pad',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0501_dialogbox_pc',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0502_dialogboxes_mob',
    ext: 'png',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0502_dialogboxes_mob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0502_dialogboxes_pad',
    ext: 'png',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0502_dialogboxes_pad',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0502_dialogboxes_pc',
    ext: 'png',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0502_dialogboxes_pc',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0502_picsq01_pcpadmob',
    ext: 'jpg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0502_picsq01_pcpadmob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0502_picsq02_pcpadmob',
    ext: 'jpg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0502_picsq02_pcpadmob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0601_dialogbox_mob',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0601_dialogbox_pad',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0601_dialogbox_pc',
    ext: 'svg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0601_picsq01_mob',
    ext: 'jpg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0601_picsq01_mob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0602_picsq01_mob',
    ext: 'jpg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0602_picsq01_mob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0602_picsq01_pcpad',
    ext: 'jpg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0602_picsq01_pcpad',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0602_picsq02_pcpad',
    ext: 'jpg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0602_picsq02_pcpad',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0602_picsq03_pcpad',
    ext: 'jpg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0602_picsq03_pcpad',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0602_picsq04_pcpad',
    ext: 'jpg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0602_picsq04_pcpad',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0602_picsq05_pcpad',
    ext: 'jpg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0602_picsq05_pcpad',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0602_picsq06_pcpad',
    ext: 'jpg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0602_picsq06_pcpad',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0603_picsq01_mob',
    ext: 'jpg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0603_picsq01_mob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0604_picsq01_mob',
    ext: 'jpg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0604_picsq01_mob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0605_picsq01_mob',
    ext: 'jpg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0605_picsq01_mob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
  {
    src: '/img/intimate_relationships_p0606_picsq01_mob',
    ext: 'jpg',
    srcset: undefined,
    use2x: false,
    webp: false,
  },
  {
    src: '/img/intimate_relationships_p0606_picsq01_mob',
    ext: 'webp',
    srcset: undefined,
    use2x: false,
    webp: true,
  },
]);
</script>

<template>
  <div class="w-full p-10">
    <div class="flex gap-4 flex-wrap">
      <div
        v-for="(item, index) in testImages"
        :key="index"
        class="flex items-center justify-center w-[100px] h-[100px] bg-gray-50"
      >
        <LPic
          :src="item.src"
          :srcset="item.srcset"
          :ext="item.ext"
          :use-prefix="item.usePrefix"
          :use2x="false"
          :webp="item.webp"
        />
      </div>
    </div>
  </div>
</template>
